export const classList = {
    0: "Hero",
    1: "Bandit",
    2: "Astrologer", 
    3: "Warrior", 
    4: "Prisoner",
    5: "Confessor", 
    6: "Wretch", 
    7: "Vagabond", 
    8: "Prophet", 
    9: "Samurai"  
}

export const weaponsList = {
    0: "Axes", 
    1: "Bows or Crossbows", 
    2: "Claws", 
    3: "Daggers", 
    4: "Colossal Weapons", 
    5: "Fists",
    6: "Flails", 
    7: "Staff", 
    8: "Spears", 
    9: "Greatswords",
    10: "Halberds",
    11: "Hammers",
    12: "Thrusting Weapons",
    13: "Katanas",
    14: "Scythes",
    15: "Shields",
    16: "Straight Swords",
    17: "Whips",
    18: "Twinblades",
    19: "Catalyst",
    20: "Seal",
    21: "Curved Swords",
}

export const passiveList = {
    0: "Cant wear headpiece", 
    1: "Armor must match", 
    2: "No starting keepsake", 
    3: "Cant change Ash of War",
    4: "Must light roll (<30% load)", 
    5: "Weapon must apply bleed buildup", 
    6: "Cannot go above 30 vigor", 
    7: "Strength and dex must be equal", 
    8: "Cannot level dex",
    9: "Cannot level str",
    10: "Same number of crimson/cerullean vials",
    11: "Only skeleton summons allowed",
    12: "Must keep starting Armor",
    13: "Cannot wear pants",
    14: "Only beast summons are allowed",
    15: "Not allowed to use shops",
    16: "Must keep 1 talisman slot empty", 
    17: "Not allowed to recover runes", 
    18: "Can't pickup maps", 
    19: "Max soul level of 100", 
    20: "No summoning (players or ashes)",
    21: "Must aquire all great runes before end of game",
}
